In [ ]:
a=10
b=20
c=float(a)
print(a,b,c)
print(type(a))
print(type(b))
print(type(c))

10 20 10.0
<class 'int'>
<class 'int'>
<class 'float'>


In [ ]:
 s = "CloudEducation"
 print(s[-1:])
 print(s[:3])
 print(s[7:])
 print(s[-2:])

n
Clo
ucation
on


In [ ]:
s="cloud"
print(s.lower())

cloud


In [ ]:
s="cloud"
print(s.upper())

CLOUD


In [ ]:
s="shivalik"
dir=(s)
print(s.upper())

SHIVALIK


In [ ]:
s="cloud , education"
split_values= s.split(",")
print(split_values)

['cloud ', ' education']


In [ ]:
a=10
b= 20
c=a>b
print(c)
print(type(c))

False
<class 'bool'>


In [ ]:
a=10
b=20
c=40
result_addition= a+b+c
print('the result of a+b+c is', result_addition)

the result of a+b+c is 70


In [ ]:
w=10
z=29
h='the result of w+z is '
result_addition= w+z
print(h,result_addition)

the result of w+z is  39


In [ ]:
result_modulus=w%z
print('the result of w % z is', result_modulus)

the result of w % z is 10


In [ ]:
result_subtraction=w-z
print('the result of w-z is ', result_subtraction)

the result of w-z is  -19


In [ ]:
result_multiplication=w*z
print('the result of w*z is ',result_multiplication)

the result of w*z is  290


In [ ]:
a=10
b=20
result_equal=a==b
print('the result of a == b is', result_equal)

the result of a == b is False


In [ ]:
result_not_equal =a!=b
print('the resulto of a !=b is ', result_not_equal)

the resulto of a !=b is  True


In [ ]:
a=10
b=20
print('a=',a)
print('b=',b)

a= 10
b= 20


In [ ]:
a+=b
print('the result of a+=b is',a)

the result of a+=b is 50


In [ ]:
a=10
a-=b
print('the result of a-=b is',a)

the result of a-=b is -10


In [ ]:
a=10
a*=b
print('the result of a*=b',a)

the result of a*=b 200


In [ ]:
a=1
b=(1,2,3,6,5)
print('the result of a in b is',a in b)

the result of a in b is True


In [ ]:
print('the resultof a not in b is ', a not in b)

the resultof a not in b is  False


In [ ]:
x=[1,2,3]
y=[1,2,3]
result_is = x is y
print('the result of x is y :',result_is)

the result of x is y : False


In [ ]:
my_list=[1,2,3,4,5,6]
subset=my_list[1:4]
print( subset )
subset=my_list[4:]
print( subset )

[2, 3, 4]
[5, 6]


In [ ]:
my_list=[1,2,3,4,5]
my_list[2]=10
print("the modified list:",my_list)
my_list[0]= 'sandeep'
print("the modified list:",my_list)

the modified list: [1, 2, 10, 4, 5]
the modified list: ['sandeep', 2, 10, 4, 5]


In [ ]:
my_list=[1,2,3,4,5]
my_list[2]=30
print("the new list:",my_list)
my_list[1]='SHIVALIK COLLEGE'
print("the new list:",my_list)
b_list=[6,7,8,9,10]
c_list=my_list + b_list
print("the sum two list is :", c_list)

the new list: [1, 2, 30, 4, 5]
the new list: [1, 'SHIVALIK COLLEGE', 30, 4, 5]
the sum two list is : [1, 'SHIVALIK COLLEGE', 30, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
x=10
y=20
z='the result of x+z is'
result_addition=x+y
print(z,result_addition)

the result of x+z is 30


In [ ]:
result_multiplication= x*y
print('the result of x*y is ', result_multiplication)
result_subtraction=x-y
print('the result x-y', result_subtraction)


the result of x*y is  200
the result x-y -10


In [ ]:
for a in ' sandeep':
  print(a)

 
s
a
n
d
e
e
p


In [ ]:
num1=20
num2=30
num3=40
if((num1>num2)and (num1>num)):
  print(num1,"is the largest num")
  elif((num2>num)and(num2>num)):
  print(num2,"is the largest num")
  else:
  print(num3," is the largest num")





SyntaxError: invalid syntax (<ipython-input-12-23b2cc7a18eb>, line 6)

In [ ]:
import numpy as np
arr_1d= np.array([1,2,3,4,5,6,7,])
print("this is an one d array")
print(arr_1d)

this is an one d array
[1 2 3 4 5 6 7]


In [ ]:
arr_2d= np.array([[1,2,3,4],[5,6,7,8]])
print("this is an 2d array")
print(arr_2d)
arr_2d.ndim

this is an 2d array
[[1 2 3 4]
 [5 6 7 8]]


2

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
shape=arr.shape
print(shape)
reshaped_arr=arr.reshape((2,3))
print(reshaped_arr)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
random_array=np.random.rand(3,3)
print(random_array)

[[0.62090933 0.79307662 0.88869466]
 [0.57919859 0.62874503 0.88065647]
 [0.93575136 0.14305394 0.21228078]]


In [ ]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6,])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [ ]:
#find all indices with value greater  than 50
a = np.array([45,23,45,65,32,76,32,65,4,5,45,23,65,65,24,11,21,21,12,23,232,32])
np.where(a>50)



array([45, 23, 45, 65,  0,  0,  0, 65,  0,  5, 45, 23, 65, 65,  0, 11, 21,
       21,  0, 23,  0,  0])

In [ ]:
np.where(a>50,0,a)

array([45, 23, 45,  0, 32,  0, 32,  0,  4,  5, 45, 23,  0,  0, 24, 11, 21,
       21, 12, 23,  0, 32])

In [ ]:
np.where(a%2==0,0,a)

array([45, 23, 45, 65,  0,  0,  0, 65,  0,  5, 45, 23, 65, 65,  0, 11, 21,
       21,  0, 23,  0,  0])

In [ ]:
a

array([ 45,  23,  45,  65,  32,  76,  32,  65,   4,   5,  45,  23,  65,
        65,  24,  11,  21,  21,  12,  23, 232,  32])

In [ ]:
np.argmax(a)

20

In [ ]:
b=np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.argmax(b,axis=0)

array([3, 3, 3, 3])

In [ ]:
np.argmax(b,axis=1)

array([3, 3, 3, 3])

In [ ]:
np.argmin(a,axis=0)

8

In [ ]:
#np.cumsum
a

array([ 45,  23,  45,  65,  32,  76,  32,  65,   4,   5,  45,  23,  65,
        65,  24,  11,  21,  21,  12,  23, 232,  32])

In [ ]:
np.cumsum(a)

array([ 45,  68, 113, 178, 210, 286, 318, 383, 387, 392, 437, 460, 525,
       590, 614, 625, 646, 667, 679, 702, 934, 966])

In [ ]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#import pandas as pd
